### ISSUE TITLE
ur bot sucks

### ISSUE THREAD

**Issue by jennocides** [mynameisivan/discord-bot#3]
is big slow 5k ping

**Comment by BrandonWLee** [comment]
To be clear, the issue was the response time from BOT Alfred seemed to always take ~5 seconds whereas bb-bot was much quicker.

The issue should be resolved:
![image](https://user-images.githubusercontent.com/734576/87512218-7bbb7e80-c62b-11ea-8f1d-e951568e56cb.png)

The slowdown was caused by some DNS resolution issues on @mynameisivan's network (where BOT Alfred resides). @mynameisivan to provide more details (if he wants).

**Comment by mynameisivan** [comment]
Fix was to remove faulty DNS server from the instance's `/etc/resolv.conf`

```
nameserver 192.168.1.3 <-- bad one
nameserver 192.168.1.4
nameserver 192.168.1.5
```
The faulty one was causing a 5s timeout before resolving to the next DNS server. Example in resolution below:

```
root@discord:~/discord-bot# time dig +short google.com @192.168.1.3
;; connection timed out; no servers could be reached

real    0m15.040s
user    0m0.023s
sys     0m0.020s
```
```
root@discord:~/discord-bot# time dig +short google.com @192.168.1.4
216.58.194.174

real    0m0.036s
user    0m0.017s
sys     0m0.017s
```
I've updated the network settings to persist removal and will continue to debug the faulty DNS server.
